version: '3.8'

services:
  musics.presentation:
    container_name: musics_presentation_container
    image: musics.presentation
    build:
      context: ../
      dockerfile: src/Backend/MusicS.Presentation/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=musicsdb;Username=sunday;Password=sunday
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: musics_db_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sunday
      POSTGRES_PASSWORD: sunday
      POSTGRES_DB: musicsdb
      TZ: Europe/Moscow
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: unless-stopped

